export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as NotFound404} from './NotFound404'
export {default as Profile} from './Profile'
export {default as ProfileForm} from './ProfileForm'
export {default as PostForm} from './PostForm'
export {default as PostDetail} from './PostDetail'